# Generated by Django 3.2.6 on 2021-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
