# Generated by Django 3.2.6 on 2021-10-06 22:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
