# Generated by Django 3.2.9 on 2022-01-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211205_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao_arquivo1',
            field=models.CharField(default='arquivo11', max_length=50),
        ),
    ]
