# Generated by Django 3.2.9 on 2022-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_post_descricao_arquivo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao_arquivo1',
            field=models.CharField(blank=True, default='arquivo1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao_arquivo2',
            field=models.CharField(blank=True, default='arquivo2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao_arquivo3',
            field=models.CharField(blank=True, default='arquivo3', max_length=50, null=True),
        ),
    ]
