# Generated by Django 3.2.9 on 2022-01-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220114_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='arquivo1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='arquivo2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='arquivo3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
